services:
  oasipdbbooking:
    container_name: oasipdbbooking
    image: mysql/mysql-server:8.0.29
    volumes:
      - type: bind
        source: ./etc/my.cnf
        target: /etc/my.cnf
      - type: bind
        source: ./datadir
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=int221_at3
      - MYSQL_DB_HOST=int221-at3-server
      - MYSQL_DB_USER=root
    ports:
      - "3306:3306"

  backend1:
    container_name: backend1
    image: backend
    build:
      context: ./back-end/At-3-Booking
    ports:
      - "8443:8443"
    environment:
      - spring.datasource.url=jdbc:mysql://oasipdbbooking:3306/booking
    depends_on:
      - oasipdbbooking
    restart: on-failure

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./font-end/OASIP-AT-3-FEnd
    depends_on:
      - oasipdbbooking
      - backend1
    ports:
      - "3000:80"

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverseproxy
    depends_on:
      - oasipdbbooking
      - backend1
      - frontend
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/ssl/www-at3.crt:/etc/ssl/certs/www-at3.crt
      - ./reverse-proxy/ssl/privatekey.key:/etc/ssl/private/privatekey.key
    ports:
      - "80:80"
      - "443:443"
