services:
  oasipdbbooking:
    container_name: oasipdbbooking
    image: mysql/mysql-server:latest
    volumes:
      - type: bind
        source: ./etc/my.cnf
        target: /etc/my.cnf
      - type: bind
        source: ./datadir
        target: /var/lib/mysql
    environment:
      - MYSQL_PASSWORD=int221_at3
      - MYSQL_DB_HOST=int221-at3-server
      - MYSQL_DB_USER=root
    ports:
      - "3306:3306"

  backend:
    container_name: backend
    image: backend
    build:
      context: ./At-3-Booking
    ports:
      - "5000:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://oasipdbbooking:3306/booking
    depends_on:
      - oasipdbbooking
    restart: on-failure

  server-test:
    container_name: server-test
    image: backend-intregate
    build:
      context: ./backend-intregate
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://oasipdbbooking:3306/booking
    depends_on:
      - oasipdbbooking
    restart: on-failure

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./OASIP-AT-3-FEnd
    depends_on:
      - oasipdbbooking
      - backend
    ports:
      - "80:80"

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverseproxy
    depends_on:
      - oasipdbbooking
      - backend
      - frontend
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
