name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: mysql/mysql-server:8.0.29
    steps:
    - uses: actions/checkout@v3
    - name: Run docker-compose
      run: sudo docker-compose up -d --build
  
